In [1]:
from keras import Sequential

In [2]:
from keras.layers import Dense, SimpleRNN

In [3]:
model = Sequential()

In [4]:
model.add(SimpleRNN(3,input_shape=(4,5))) #4 lenth of the sentence (highest one) #5= total no of vocabulary #we will pass word vectors to RNN in different timestamps
model.add(Dense(1,activation='sigmoid'))

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
model.get_weights()

[array([[-0.7850744 , -0.556292  ,  0.34003955],
        [ 0.4253809 ,  0.6144137 , -0.22930604],
        [ 0.31983775,  0.67090195,  0.37165898],
        [-0.08461386,  0.3334326 , -0.549876  ],
        [ 0.25198048,  0.42890543,  0.8118854 ]], dtype=float32),
 array([[ 0.13897967, -0.66101307,  0.73739165],
        [-0.8609186 , -0.44862878, -0.23989892],
        [ 0.48939145, -0.601493  , -0.63142866]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.5756955],
        [-0.6401658],
        [-0.7935748]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
model.get_weights()[0]

array([[-0.7850744 , -0.556292  ,  0.34003955],
       [ 0.4253809 ,  0.6144137 , -0.22930604],
       [ 0.31983775,  0.67090195,  0.37165898],
       [-0.08461386,  0.3334326 , -0.549876  ],
       [ 0.25198048,  0.42890543,  0.8118854 ]], dtype=float32)

In [8]:
model.get_weights()[0].shape # for Feed forward

(5, 3)

In [9]:
model.get_weights()[1].shape # for feedback

(3, 3)

In [10]:
from keras.datasets import imdb
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [12]:
import numpy as np
np.array(X_train).shape

(25000,)

In [13]:
X_test.shape

(25000,)

In [14]:
sent = [
    'India won the world',
    'Rohit played very well',
    'Above all is my imagination',
    'India is great',
    'definately we win next worldcup'
]

In [15]:
from keras.preprocessing.text import Tokenizer #performs integer incoding
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sent)
tokenizer.word_index

{'india': 1,
 'is': 2,
 'won': 3,
 'the': 4,
 'world': 5,
 'rohit': 6,
 'played': 7,
 'very': 8,
 'well': 9,
 'above': 10,
 'all': 11,
 'my': 12,
 'imagination': 13,
 'great': 14,
 'definately': 15,
 'we': 16,
 'win': 17,
 'next': 18,
 'worldcup': 19}

In [16]:
tokenizer.word_counts

OrderedDict([('india', 2),
             ('won', 1),
             ('the', 1),
             ('world', 1),
             ('rohit', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 2),
             ('my', 1),
             ('imagination', 1),
             ('great', 1),
             ('definately', 1),
             ('we', 1),
             ('win', 1),
             ('next', 1),
             ('worldcup', 1)])

In [17]:
tokenizer.document_count

5

In [19]:
encoding = tokenizer.texts_to_sequences(sent)

In [21]:
#converting all sentences into same length
from keras.utils import pad_sequences
pad_sequences(encoding,padding='post')

array([[ 1,  3,  4,  5,  0],
       [ 6,  7,  8,  9,  0],
       [10, 11,  2, 12, 13],
       [ 1,  2, 14,  0,  0],
       [15, 16, 17, 18, 19]], dtype=int32)

In [22]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [24]:
mylist=[]
for i in X_train:
  mylist.append(len(i))
min(mylist)

11

In [25]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [26]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(50,1)))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [27]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5)

Epoch 1/5
782/782 [==============================] - 34s 39ms/step - loss: 0.6945 - accuracy: 0.5049 - val_loss: 0.6943 - val_accuracy: 0.5024
Epoch 2/5
782/782 [==============================] - 31s 39ms/step - loss: 0.6930 - accuracy: 0.5050 - val_loss: 0.6946 - val_accuracy: 0.5027
Epoch 3/5
782/782 [==============================] - 33s 42ms/step - loss: 0.6928 - accuracy: 0.5106 - val_loss: 0.6983 - val_accuracy: 0.5022
Epoch 4/5
782/782 [==============================] - 30s 39ms/step - loss: 0.6938 - accuracy: 0.5058 - val_loss: 0.6945 - val_accuracy: 0.5034
Epoch 5/5
782/782 [==============================] - 30s 39ms/step - loss: 0.6929 - accuracy: 0.5011 - val_loss: 0.6961 - val_accuracy: 0.5024


In [28]:
model.predict(X_test)

782/782 [==============================] - 5s 6ms/step


array([[0.4818063],
       [0.4818063],
       [0.4818063],
       ...,
       [0.4818063],
       [0.4818063],
       [0.4818063]], dtype=float32)

In [29]:
model.evaluate(X_test,y_test)

782/782 [==============================] - 5s 6ms/step - loss: 0.6961 - accuracy: 0.5024


[0.6961308717727661, 0.5023999810218811]

In [30]:
loss,accuracy = model.evaluate(X_test,y_test)
loss

782/782 [==============================] - 5s 7ms/step - loss: 0.6961 - accuracy: 0.5024


0.6961308717727661