In [2]:
import pandas as pd
import re

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Ankit152/IMDB-sentiment-analysis/master/IMDB-Dataset.csv')
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

# Text Preprocessing

In [4]:
import string
# removing the html tags
def clean_html(text):
    clean=re.compile('<.*?>')
    cleantext=re.sub(clean,'',text)
    return cleantext

# first round of cleaning
def clean_text1(text):
    text=text.lower()
    text=re.sub('\[.*?\]','',text)
    text=re.sub('[%s]'%re.escape(string.punctuation),'',text)
    text=re.sub('\w*\d\w*','',text)
    return text

# second round of cleaning
def clean_text2(text):
    text=re.sub('[''"",,,]','',text)
    text=re.sub('\n','',text)
    return text

cleaned_html=lambda x:clean_html(x)
cleaned1=lambda x:clean_text1(x)
cleaned2=lambda x:clean_text2(x)

df['review']=pd.DataFrame(df.review.apply(cleaned_html))
df['review']=pd.DataFrame(df.review.apply(cleaned1))
df['review']=pd.DataFrame(df.review.apply(cleaned2))

df.head()


review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [5]:
import pandas as pd
import re

df = pd.read_csv('https://raw.githubusercontent.com/Ankit152/IMDB-sentiment-analysis/master/IMDB-Dataset.csv')
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df1 = df.iloc[:10000]
df1.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
#a particular movie review
df1['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [8]:
df1['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [9]:
df1.isnull().sum()

review       0
sentiment    0
dtype: int64

In [10]:
df1.duplicated().sum()

17

In [11]:
df1.drop_duplicates(inplace=True)

<ipython-input-11-1788250b656d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop_duplicates(inplace=True)


# Text Preprocessing

In [12]:
import string
# removing the html tags
def clean_html(text):
    clean=re.compile('<.*?>')
    cleantext=re.sub(clean,'',text)
    return cleantext

# first round of cleaning
def clean_text1(text):
    text=text.lower()
    text=re.sub('\[.*?\]','',text)
    text=re.sub('[%s]'%re.escape(string.punctuation),'',text)
    text=re.sub('\w*\d\w*','',text)
    return text

# second round of cleaning
def clean_text2(text):
    text=re.sub('[''"",,,]','',text)
    text=re.sub('\n','',text)
    return text

cleaned_html=lambda x:clean_html(x)
cleaned1=lambda x:clean_text1(x)
cleaned2=lambda x:clean_text2(x)

df1['review']=pd.DataFrame(df1.review.apply(cleaned_html))
df1['review']=pd.DataFrame(df1.review.apply(cleaned1))
df1['review']=pd.DataFrame(df1.review.apply(cleaned2))
df1.head()

<ipython-input-12-32045e2a9e91>:26: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['review']=pd.DataFrame(df1.review.apply(cleaned_html))
<ipython-input-12-32045e2a9e91>:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['review']=pd.DataFrame(df1.review.apply(cleaned1))
<ipython-input-12-32045e2a9e91>:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pan

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [13]:
df1.value_counts('sentiment')

sentiment
positive    5023
negative    4960
Name: count, dtype: int64

In [14]:
X = df1.iloc[:,0:1]
y = df1['sentiment']

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
#Applying BOW
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [18]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [19]:
X_train_bow.shape

(7986, 70705)

In [20]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB
gnb = GaussianNB()
gnb.fit(X_train_bow,y_train)

GaussianNB()

In [21]:
#Gaussian Naive Bayes
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6364546820230346
[[714 267]
 [459 557]]
              precision    recall  f1-score   support

           0       0.61      0.73      0.66       981
           1       0.68      0.55      0.61      1016

    accuracy                           0.64      1997
   macro avg       0.64      0.64      0.63      1997
weighted avg       0.64      0.64      0.63      1997



In [22]:
#Multinomial Naive Bayes (used for text data)
mnb = MultinomialNB()
mnb.fit(X_train_bow,y_train)

y_pred1 = mnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

0.8382573860791187
[[866 115]
 [208 808]]
              precision    recall  f1-score   support

           0       0.81      0.88      0.84       981
           1       0.88      0.80      0.83      1016

    accuracy                           0.84      1997
   macro avg       0.84      0.84      0.84      1997
weighted avg       0.84      0.84      0.84      1997



In [23]:
#applying Random forest
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train_bow,y_train)

y_pred2 = rfc.predict(X_test_bow)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))


0.8352528793189785
[[818 163]
 [166 850]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       981
           1       0.84      0.84      0.84      1016

    accuracy                           0.84      1997
   macro avg       0.84      0.84      0.84      1997
weighted avg       0.84      0.84      0.84      1997



In [24]:
#Using most common words in BOW
cv = CountVectorizer(max_features=3000)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()
rf.fit(X_train_bow,y_train)

y_pred3 = rf.predict(X_test_bow)
print(accuracy_score(y_test,y_pred3))

0.8372558838257386


In [25]:
#Using n_gram

cv = CountVectorizer(ngram_range=(1,3),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()
rf.fit(X_train_bow,y_train)

y_pred4 = rf.predict(X_test_bow)
print(accuracy_score(y_test,y_pred4))

0.842764146219329


In [26]:
#Applying TF-IDF (Used for information retrival system)

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review']).toarray()

rf = RandomForestClassifier()
rf.fit(X_train_tfidf,y_train)

y_pred5 = rf.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred5))

0.8352528793189785


In [28]:
#Applying word2vec

import gensim
from gensim.models import Word2Vec
from nltk import sent_tokenize,word_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')

story = []
for doc in df1['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

model = Word2Vec(story,min_count=2,window = 10)

model.build_vocab(story)
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


(8074639, 10732480)

In [29]:
len(model.wv.index_to_key)

35204

In [33]:
import numpy as np
def document_vector(doc):
  #removing out of vocab words
  doc = [word for word in doc.split() if word in model.wv.index_to_key]
  return np.mean(model.wv[doc],axis=0)

In [34]:
document_vector(df1['review'].values[0])

array([ 0.5341227 , -0.5259036 , -0.42644593, -0.29323834,  0.0611665 ,
       -0.42988026, -0.26446283,  0.21958923, -0.19650136,  0.896175  ,
       -0.8956365 , -1.1525815 ,  0.2765006 , -0.27773494, -0.04259543,
        0.13624765, -0.3906313 ,  0.40110537,  0.30780277,  0.46135247,
        0.10414671, -0.4297246 , -0.3965115 , -0.5750964 ,  0.10420732,
       -0.3327316 , -0.4253979 , -0.80692595, -0.14639363, -0.84735346,
       -0.5803283 ,  0.5412628 ,  0.2027154 , -0.11272173,  0.71404487,
        0.7517887 , -0.2751152 ,  0.29277265,  0.36109537, -0.9127333 ,
       -0.43324372,  0.34569398,  0.7492784 , -0.07158961, -0.38574132,
       -0.00418927,  0.13554615, -0.04494483,  0.37444362, -0.8421729 ,
       -0.14362447, -0.34767678,  0.6182591 ,  0.16626625,  0.45418146,
        0.24756981, -0.24673776,  0.3448936 ,  0.4282312 ,  0.08986166,
        0.44638935, -0.26372933,  0.2339137 ,  0.15951514, -0.3791892 ,
       -0.46292073,  0.46458063,  0.19024232,  0.97103894,  0.06

In [37]:
from tqdm import tqdm
X = []
for doc in tqdm(df1['review'].values):
  X.append(document_vector(doc))

100%|██████████| 9983/9983 [05:38<00:00, 29.46it/s]


In [38]:
type(X)

list

In [39]:
X = np.array(X)
X.shape

(9983, 100)

In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df1['sentiment'])
y

array([1, 1, 1, ..., 0, 0, 1])

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)

y_pred6 = rfc.predict(X_test)
print(accuracy_score(y_test,y_pred6))

0.7921882824236355
